// This file is automatically generated. Small dev-time guard added so the
// app doesn't crash when VITE_SUPABASE_* env vars are not set (e.g. in a
// development environment where the user hasn't configured Supabase yet).
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function makeMockBuilder(result: any = { data: [], error: null }) {
  const builder: any = {
    select() { return builder; },
    eq() { return builder; },
    order() { return builder; },
    maybeSingle() { return builder; },
    limit() { return builder; },
    insert() { return builder; },
    update() { return builder; },
    delete() { return builder; },
    then(onFulfill: any, onReject: any) { return Promise.resolve(result).then(onFulfill, onReject); },
    catch() { return Promise.resolve(result); }
  };
  return builder;
}

function makeMockSupabase() {
  // Simple in-memory auth simulation
  let currentSession: any = null;
  const listeners: Array<any> = [];

  const auth = {
    getSession: async () => ({ data: { session: currentSession } }),
    onAuthStateChange: (cb: any) => {
      listeners.push(cb);
      return { data: { subscription: { unsubscribe: () => { const i = listeners.indexOf(cb); if (i !== -1) listeners.splice(i, 1); } } } };
    },
    signInWithPassword: async ({ email, password }: any) => {
      // naive accept any credentials in mock
      currentSession = { user: { id: 'mock-user-id', email } };
      // notify listeners: (event, session)
      listeners.forEach((cb) => { try { cb('SIGNED_IN', currentSession); } catch (e) {} });
      return { data: { session: currentSession }, error: null };
    },
    signUp: async ({ email }: any) => {
      currentSession = { user: { id: 'mock-user-id', email } };
      listeners.forEach((cb) => { try { cb('SIGNED_IN', currentSession); } catch (e) {} });
      return { data: { user: currentSession.user }, error: null };
    },
    signOut: async () => {
      currentSession = null;
      listeners.forEach((cb) => { try { cb('SIGNED_OUT', null); } catch (e) {} });
      return { error: null };
    }
  };

  // Simple channel system to simulate Realtime subscriptions
  const channels: any[] = [];

  function createChannel(name: string) {
    const channel: any = {
      name,
      handlers: [] as any[],
      _subscribed: false,
      on(event: string, filter: any, cb: any) {
        // allow on(event, handler) and on(event, filter, handler)
        let handler = cb;
        let cfg = filter;
        if (typeof filter === 'function') {
          handler = filter;
          cfg = null;
        }
        this.handlers.push({ event, filter: cfg, cb: handler });
        return this;
      },
      subscribe() {
        this._subscribed = true;
        channels.push(this);
        return this;
      },
      unsubscribe() {
        this._subscribed = false;
        const i = channels.indexOf(this);
        if (i !== -1) channels.splice(i, 1);
      },
      // helper to simulate an event
      _emit(payload: any) {
        this.handlers.forEach((h: any) => {
          try { h.cb(payload); } catch (e) {}
        });
      }
    };
    return channel;
  }

  return {
    from: (_: string) => makeMockBuilder(),
    rpc: async () => ({ data: [], error: null }),
    auth,
    channel: (name: string) => createChannel(name),
    removeChannel: (ch: any) => { try { ch.unsubscribe(); } catch (e) {} }
  } as any;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Require real Supabase credentials in this environment. Do not fall back to mocks.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY must be set to use Supabase. Set the env vars and restart the app.');
}

const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export { supabase };